### ISSUE TITLE
error 404 while downloading lendmyphone 3 iOS 13 iphone x

### ISSUE THREAD

**Issue by dewankm96** [geometricsoftware/Bug-Tracker#10]
![IMG_1195](https://user-images.githubusercontent.com/62199794/76697594-28f2aa00-66bf-11ea-94ab-9392190a3f93.PNG)
Bought the tweak from official repo, however every time I try to download it I get this same error again and again in Sileo. Kindly provide a solution to it or a refund.

**Comment by geometricsoftware** [comment]
Should have been fixed already some time ago. Tell us if the problem still persists.
