### ISSUE TITLE
IntelligentPass3 safe mode crash when inputting passcode

### ISSUE THREAD

**Issue by Aransh** [geometricsoftware/Bug-Tracker#13]
Sometimes after a respring, while I'm connected to WiFi (one where I have the passcode disabled on), I would swipe up to unlock, and it will require a passcode, inputting it would immediately crash to safe mode, respringing back from safe mode will continue to crash when inputting passcode until I either disable WiFi or uninstall IntelligentPass3.
Cr4shed says the reason is "the new lock screen expects user authentication before unlock can happen".

Device: iPhone X🅂 Max
iOS: 13.3
Jailbreak: Unc0ver 4.3.1
IntelligentPass3 version: 1.1.3

Full crash log: [Link](https://pastebin.com/jQJ4pFT1)

**Comment by geometricsoftware** [comment]
Hello!

This is fixed in 1.2.

**Comment by Canorus** [comment]
this isn't fixed on 1.2
