### ISSUE TITLE
ModernAlerts 2 v1.0.2 freezes phone

### ISSUE THREAD

**Issue by 301nav** [geometricsoftware/Bug-Tracker#16]
Whenever there is supposed to be a dialog box with two choices eg yes/no, my phone freezes and I have to respring. Luckily I can do so with the volume buttons because I have a tweak installed to do that. It is very annoying and I only just realized a few minutes ago that this tweak was the issue. I have downgraded to 1.0.1 and the issue is not found there.

**Comment by 301nav** [comment]
also it happens on dialog boxes with the fingerprint sensor like bioprotect

**Comment by 301nav** [comment]
I think maybe it tries to bring up the alert and disable the background but the alert doesn't seem to be visible or interacted with

**Comment by geometricsoftware** [comment]
Hello!

The issue has been fixed in version 1.0.3.
