### ISSUE TITLE
Modern alerts 1.0.2 freez and reboot phone, most of windows not supported. 

### ISSUE THREAD

**Issue by ChiefFucker** [geometricsoftware/Bug-Tracker#17]
Break bioprotect， copylog ，spy ，and so on.
Most of windows can’t popup, freeze and reboot phone, break checkra1n jailbreak too .
Wtf, didn’t you test it after update? Shit

**Comment by geometricsoftware** [comment]
Hello!

The issue has been fixed in version 1.0.3.
