### ISSUE TITLE
Modern alerts made cydia freez and crash 

### ISSUE THREAD

**Issue by ChiefFucker** [geometricsoftware/Bug-Tracker#18]
If I add repo from cydown repo list, cydia will freeze and crash.
![69C651F3-7F3F-4DFB-8CEC-A6ED39866273](https://user-images.githubusercontent.com/61261180/83248491-b67e6a00-a1d7-11ea-8bd4-5c58cc4bd650.png)

**Comment by despair089** [comment]
Please use the free alternatives tweak call BlurryAlerts, ModernAlerts 2has been confirmed that it will delay your button reaction time and will not work properly in Cydia

**Comment by geometricsoftware** [comment]
Closed due to inactivity or the bug already being fixed in a newer version.
