### ISSUE TITLE
[IntelligentPass3] Bug: can't unlock when, in lockscreen, I switch to trusted wifi 

### ISSUE THREAD

**Issue by beawareoftheg** [geometricsoftware/Bug-Tracker#19]
Hello, there is a bug on IntelligentPass3 on my iPhone X with checkrain and iOS 13.5. When I am in lockscreen and I switch from a situation when the code to unlock is asked to a wifi that is trusted, the lock icon disappear as it should BUT if I swipe up to unlock it doesn't unlock and doesn't ask for passcode. The only way to unlock is to disable wifi, swipe up and insert passcode and then reenable wifi. This is very very annoying because it happen every time I came home and switch into trusted wifi with phone locked (basically every day). 
This bug is present also with "trusted" bluetooth devices.
I don't know if I explained well, if not please contact me or answer to this thread.

**Comment by MrSco** [comment]
I also have this issue in addition to crashes...

https://github.com/geometricsoftware/Bug-Tracker/issues/20#issuecomment-640864919

**Comment by beawareoftheg** [comment]
I don’t get crashes, but it still doesn’t ask me for passcode and I can unlock only by turning off wifi (or bluetooth, depending on the case) insert the passcode and then, with iPhone unlocked, enable again wifi/bluetooth, and it’s so annoying..

**Comment by geometricsoftware** [comment]
Hello!

This issue has been addressed in version 1.2.1 based on the description you provided. Can you please update and tell us if it solved your issue.

Thank you.

**Comment by MrSco** [comment]
I just tested and it seems to work ok now. I'll keep my eye on it for the next day or two and report back if the crash/issue happens again.

Thanks

**Comment by beawareoftheg** [comment]
Awesome!! Thank you!
