### ISSUE TITLE
[IntelligentPass3] Safe mode after install

### ISSUE THREAD

**Issue by Zamua** [geometricsoftware/Bug-Tracker#21]
iPhone X, iOS 13.5, unc0ver 5.0.1

After purchasing and installing it, it worked briefly. Perhaps a few hours. Then I installed some updates from Zebra for some other tweaks. Those tweaks were Photon, Hub, Flow. Suddenly my phone went into safe mode. I was unable to get it out of safe mode after a few resprings, icleaner runs, restarts. I removed Photon, Hub, Flow and it didn't fix anything. I removed IntelligentPass3 and it resolved the issue.

**Comment by romangod90** [comment]
**iPhone 11 Pro Max, iOS 13.5**
Same issue. Worked fine for a few hours after install, then continually crashed into safe mode. Uninstalled and the problem resolved.  Provided link to crash log. [Intelligentpass3 Crash Log](https://drive.google.com/file/d/1uvzU4mGZb565mGxF-NnAGoci3P7pl3Fc/view?usp=drivesdk)

**Comment by geometricsoftware** [comment]
Hello!

This issue has been addressed in version 1.2.1 based on the description you provided. Can you please update and tell us if it solved your issue.

Thank you.

**Comment by Zamua** [comment]
Hello! Thanks for working on this. After installing it my device goes into safe mode and I’m unable to get out of safe mode. Here’s the crash log

https://pastebin.com/wF5U6kiD

Uninstalling it resolves the issue on my device iPhone X ios13.5 unc0ver 5.0.1

**Comment by geometricsoftware** [comment]
Can you please send us an email with your Github username so we know it is you, and we can send a beta build right away to you? Our email is support@geometricsoftware.se.

**Comment by Zamua** [comment]
Email sent!

**Comment by geometricsoftware** [comment]
Issue is confirmed to be fixed in 1.2.2. :)

**Comment by Zamua** [comment]
Thanks for your excellent work!
