### ISSUE TITLE
Intelligent Pass 3 Lockscreen Bugged

### ISSUE THREAD

**Issue by Duculet** [geometricsoftware/Bug-Tracker#24]
I have discovered a strange bug where the phone can no longer be unlocked. The situations in which this happens are when WIFI unlock is enabled, I leave my house, the phone disconnects from wifi, it starts asking for the code, but sometimes when I return home and reconnect to the wifi, it simply won't unlock anymore. When I slide up to unlock it just bounces up a bit, but no unlock or code request... basically gets stuck there until reboot. I am using an iPhone X on iOS 13.5.

**Comment by beawareoftheg** [comment]
#19  I also have this problem

**Comment by MrSco** [comment]
Still no fix or update from the dev on this issue?! 

In the meantime as a workaround, you can turn on airplane mode and then it will properly prompt for your passcode. Then you can turn off airplane mode.

**Comment by beawareoftheg** [comment]
Yep, stil no fix, I don’t think they even look at this page at all!

**Comment by MrSco** [comment]
this seems like a serious bug to have for a PAID tweak.

**Comment by Duculet** [comment]
> this seems like a serious bug to have for a PAID tweak.

Well yes, kinda is :/

**Comment by geometricsoftware** [comment]
Hi!

We are working on fixing this issue right now. If you could provide any more steps that could help us, we would appreciate that.

Thank you.

**Comment by beawareoftheg** [comment]
Thank you for your support.
The best way to describe the bug is:
when the iPhone is locked and you switch from untrusted situation to a trusted one (for example: the phone connect to home wifi) it should let you unlock without passcode, instead if you swipe up nothing happen despite the icon of the Lock of the lockscreen correctly disappear.
To unlock you have to disconnect from the trusted situation and then it correctly show the Lock and ask you for passcode.

**Comment by despair089** [comment]
> 嗨！
> 
> 我們正在努力解決此問題。如果您能提供更多對我們有幫助的步驟，我們將不勝感激。
> 
> 謝謝。

Please assist me to withdraw the request from 3 months ago

> Hi!
> 
> We are working on fixing this issue right now. If you could provide any more steps that could help us, we would appreciate that.
> 
> Thank you.

Please assist me to refund the request from 3 months ago

**Comment by MrSco** [comment]
https://github.com/geometricsoftware/Bug-Tracker/issues/20#issuecomment-640864919

**Comment by geometricsoftware** [comment]
The issue should be fixed in 1.2.2.
