### ISSUE TITLE
Intelligent Pass 3 Bug : When I do cc on lockscreen

### ISSUE THREAD

**Issue by s4130921** [geometricsoftware/Bug-Tracker#25]
Hello, there? I aslo sent e-mail to support@geometricsoftware.se  about this issue too.
please check out it.

If I enabled this tweak as some options that can be disabled
in the Control Center,(ex:dark mode) it has a bug. 
On lockscreen, if I call control center before entering the home screen,
my iPhone's passcode is activated. So it asks for my face or password. 
Yeah, it is nice, I also understand this happen. It could be a way to disable security.
But at this time, the iPhone is unlocked with passoword, not the face-id,
The iPhone enters safe mode. 

This is very inconvenient while wearing a mask from the outside. There are many cases where the mask cannot be removed, so there is no way to do this if I accidentally open the control center on the lock screen.

![bug](https://user-images.githubusercontent.com/67282561/85311042-c6941b80-b4ef-11ea-9b14-6fb2e4b47e47.gif)

**Comment by despair089** [comment]
Remove IntelligentPass3 and use Passby. It's good to me&you

**Comment by s4130921** [comment]
> Remove IntelligentPass3 and use Passby. It's good to me&you

Passby doesn't work. :( It has an error which could not load system. So I was looking for another tweak, and found this. I'm iPhone 11 Pro on 13.3.1 What are your model&version? Are you using passby with no problem? Thanks for replying.

**Comment by geometricsoftware** [comment]
Hello!

This issue has been addressed in version 1.2.1 based on the description you provided. Can you please update and tell us if it solved your issue.

Thank you.
