### ISSUE TITLE
[IntelligentPass 3] Ask passcode also in trusted mode after 1.2.1

### ISSUE THREAD

**Issue by beawareoftheg** [geometricsoftware/Bug-Tracker#27]
_Intelligentpass3 ver 1.2.1 (and also 1.2.2) resolve the bug that I already talk about but brought another one: after like 10 min in lockscreen in a “trusted situation” (like home wifi), if I try to unlock it ask for passcode. It should not ask for pw because it’s in a trusted situation._

EDIT:
I was wrong: it only appen if you pull down control center in lockscreen, but I think this is for security? In that case can we disable it?

**Comment by TheSolly** [comment]
I am having the same issue, the latest two version (1,2,1, 1,2,2);  is not consistent with disabling passcode on lockscreen on trusted wifi, bluetooth, etc..
And my case doesnt relate to pulling down control center ( i am currently installing 1.2.2 and double checking) . Ver 1.2 working smooth with no issues at all. Tried all the basic troubleshooting, but nothing is working.

Update: 
So far have been able to reproduce the issue with the following scenario:

Connect to your trusted wifi, lock and unlock. now faceID has been disabled properly, 
do any of the following:
1) invoke the Control Center 
2) open the camera from the lock screen
3) charge your phone wireless or with your cable

Any of the above disable InteelignetPass functionality immediately.

**Comment by beawareoftheg** [comment]
Yep you’re right. Thanks for the info.
And I think that there are more causes that make this bug to happen, because sometimes it happens with, apparently, no reason.

I hope that the developers will fix it soon, it’s worst than before...

**Comment by geometricsoftware** [comment]
Hello!

We have identified the bug and are working on a fix. Due to vacation time it can take a bit longer than usual before the update is out.

Thank you for your patience.

**Comment by TheSolly** [comment]
@geometricsoftware any updates on this please 🙏

**Comment by MrSco** [comment]
It's been some months...any progress? Is there a workaround? This bug makes this tweak unusable 😔

**Comment by geometricsoftware** [comment]
Hi!

It is still an ongoing investigation. We already have a solution in mind but it is not clean enough for us, so we will try to come up with something better in the upcoming days.

**Comment by MrSco** [comment]
Any progress?

**Comment by geometricsoftware** [comment]
Yes, could you please send us an email and we will send you a beta version.

**Comment by MrSco** [comment]
> Yes, could you please send us an email and we will send you a beta version.

mrsco@protonmail.com

**Comment by TheSolly** [comment]
@geometricsoftware can i have this too please 🙏 
Where should i send  my email?

**Comment by MrSco** [comment]
I've been testing the 1.3~beta1-11 and there is no change. Bug still exists. So you aren't missing much lol

**Comment by TheSolly** [comment]
oh, that is sad to hear. Although, expected as it still a beta :)

**Comment by TheSolly** [comment]
@geometricsoftware Hey, any update on this please 🙏 
I am using 1.2, still bugged with re-spring when entering pass-code...

**Comment by geometricsoftware** [comment]
Hi!

This issue has been adressed in version 2.0.

Thanks for your patience!
