### ISSUE TITLE
[IntelligentPass 3] Reauthentication required even while still on trusted Wi-FI when connecting to trusted bluetooth devices

### ISSUE THREAD

**Issue by beanth** [geometricsoftware/Bug-Tracker#31]
You get reprompted for FaceID even while connected to trusted Wi-Fi networks if you connect/disconnect to a trusted bluetooth device. This happens on all versions above 1.2.

**Comment by GunBrave** [comment]
I also have this issue. Turned off all settings in IP3 except for time interval (7AM-659AM), and I’m still prompted for a Face ID scan. Even tried the connected to Apple Watch setting (which is always), and it still stops me for a Face ID. It’s like after the last few updates, the tweak has been rendered unusable—downgrading for now. 

The only time the tweak works is if you unlock your phone immediately after you lock it. Leave it locked for an extended period of time (maybe > 20 minutes?), and you’ll get the Face ID scan. 

iPhone XSM 13.5 unc0ver 5.3.1

Edit: Doesn’t matter if I disconnect from a trusted Bluetooth device or any setting I choose, the tweak has just stopped working if you’re locked for an extended period of time. I’m on 1.1.3 right now and it as it should.

**Comment by MrSco** [comment]
Same here it's been broken like this for me for a while now. Any eta on a fix?

**Comment by geometricsoftware** [comment]
Hi!

It is still an ongoing investigation. We already have a solution in mind but it is not clean enough for us, so we will try to come up with something better in the upcoming days.

**Comment by geometricsoftware** [comment]
Hi!

This issue has been adressed in version 2.0.

Thanks for your patience!
