### ISSUE TITLE
Glitchy unlock on intelligentPass3 2.0

### ISSUE THREAD

**Issue by Aransh** [geometricsoftware/Bug-Tracker#35]
Since updating to version 2.0 my unlocks are very glitchy, the lock on the lockscreen will open half way, then close back, then open half way again, close, and finally open completely.
So the animation is all weird and the unlocking takes longer...
BTW all of this is while I'm not even on my "safe" environment

**Comment by geometricsoftware** [comment]
Closed due to inactivity or the bug already being fixed in a newer version.
