### ISSUE TITLE
IntelligentPass 4 Version 1.1 Not Working

### ISSUE THREAD

**Issue by BB4LIFE** [geometricsoftware/Bug-Tracker#42]
iPhone 11 Pro -  iOS 14.3
After upgrading to latest version from 1.0, the tweak stopped working. I was using it with my WiFi network and noticed after upgrading that my phone would no longer be unlocked. I tested it with a Bluetooth device and a Now Playing app and it still didn't work. However, I downgraded and everything seems to be working again.

**Comment by fenntastic** [comment]
It's the same for me. Any Solutions?

**Comment by geometricsoftware** [comment]
Closed due to inactivity or the bug already being fixed in a newer version.
