### ISSUE TITLE
iOS 14.6-14.8 Support for TweakRestrictor 

### ISSUE THREAD

**Issue by pupvoltzy** [geometricsoftware/Bug-Tracker#47]
Hello,

My guess is that TweakRestrictor _would_ work fine on these versions of iOS, but the repo does not let us install TweakRestrictor to try. Is there any way around the 403 error when attempting to install an incompatible tweak?

**Comment by geometricsoftware** [comment]
Hi!

We have no way to confirm iOS 14.6-14.8 compatibility at the moment but we have enabled 14.x compatibility so you can download it. Would you mind testing and confirming it works on 14.8, then closing this issue?

**Comment by geometricsoftware** [comment]
iOS 14.8 has been added.
