### ISSUE TITLE
Enable/Disable switcher no work 

### ISSUE THREAD

**Issue by ChiefFucker** [geometricsoftware/Bug-Tracker#6]
All of tweaks no work after jb, I try to reinstall cydia substrate returned error code:sub-process /use/libexec/cydia/cydo returned an error code (2)
Notice:JB with turn on safe mode can fix it, but I found Enable/Disable switcher no work !

This is the last one, I gave up it.
There are so much issues.
iPhone X 13.3.1

**Comment by geometricsoftware** [comment]
This is more likely a problem with your jailbreak itself.
