### ISSUE TITLE
ModernAlerts 2 BUG&Suggestions

### ISSUE THREAD

**Issue by JAMJAMJ-A-M** [geometricsoftware/Bug-Tracker#7]
BUG：1.In the SMS application, the operation is not particularly sensitive, and the alert box always takes two or three clicks to take effect(such as delete SMS).
2.In setting the iTunes Store & App Store options in the app, if I switch IDs, I can only enter the user name in the dialog box, I cannot enter the password. There is no cursor when I click the password option.
3.Many application alert box clicks are not particularly sensitive and always require one or two more clicks.
Suggestions：It is hoped that it can adapt to the dark mode and provide the theme style switching function in the dark mode.
Device and version：iPhone Xs Max iOS 13.3
Tweak list：Aperturize,Apple File Conduit 2,Apps Manager,AppSync Unified,audiorecorder XS,avlock,bioprotext XS,ccsupport,ccvpn,cloaky,colorbadges,colorbanners 3,cylinder,dleasy,filza file manager 64-bit,flyjb,icleaner pro,kalm,killx pro,libcscolorpicker,lowbatterybanner,lynx,modernalerts 2,networkdisabler,newterm,notchification,otadisabler,powerselector,realcc,simpleactivationactions,smoothcursor ios 13,snapper 2,snowboard,snowboard settings icon extension,storeswitcher 2,sylph,system info,taptapflip,ultrasound,voicechanger xs,youtube reborn,3dbadgeclear.

**Comment by despair089** [comment]
Please use the free alternatives tweak call BlurryAlerts, ModernAlerts 2has been confirmed that it will delay your button reaction time and will not work properly in Cydia
