### ISSUE TITLE
Intelligentpass3 caused respring

### ISSUE THREAD

**Issue by luanwulin** [geometricsoftware/Bug-Tracker#8]
Hi
    i am an intelligentpass3 user.recently i find out,if my phone is locked,and i enabled the bluetooth devices before.just entering the password to unlock the phone will cause springboard respring.
   can you fix this problem.thx a lot

**Comment by xinnan** [comment]
Having the same issue

**Comment by jaxon0523** [comment]
same issue here
in my iPX 13.3.1 checkra1n 0.9.7

**Comment by geometricsoftware** [comment]
Hello!

This issue has been fixed in version 1.2.
