### ISSUE TITLE
Lendmyphone 3 conflict with other tweaks

### ISSUE THREAD

**Issue by S1lverine** [geometricsoftware/Bug-Tracker#9]
Hey,
Wonderful tweak you’ve made!
When LendMyPhone 3 is activated some other tweaks will not work both in main mode and guest mode. No crash or anything it’s like they’re not even installed. The affected tweaks I’ve noticed so far are Safari Plus, keyboardaccio and relocate by nepeta. I have respringed, restarted, reinstalled and cleaned with icleaner but no luck. It’s not even enough to turn off LendMyPhone in the settings.
The only solution I’ve found is to turn off LendMyPhone in package dylibs.

**Comment by geometricsoftware** [comment]
Closed due to inactivity or the bug already being fixed in a newer version.
